### ISSUE TITLE
Could Method websocketServerEvent be public?

### ISSUE THREAD

**Issue by maxdee** [alexandrainst/processing_websockets#1]
Great library! I am using it in one of my projects to make a webpage GUI that controls a Processing sketch. Works really well and requires no other dependencies. How would you feel about making the callback method public instead of private? (`private Method websocketServerEvent;`) I would like to set my own instead of having to have the callback in my main PApplet. Let me know, I could fork and request.

**Comment by lassevestergaard** [comment]
Hi MaxD

I'm really happy that you find the library usable! It would be great to experience what you are creating with the library. If you at any point get a video recording or the like, please drop me a link :-) 

Your suggestion is interesting, but I need you to elaborate the use case a little more before I completely understand the need. Is it because you want to create your own Processing library that extends the Websockets library? I guess it would also make sense to make the "private Method webSocketEvent;" (in WebsocketClient.java) public as well then?

Feel free to make a pull request. I can then take a look at what your intet is.

**Comment by maxdee** [comment]
Exactly, I would simply like to be able to encapsulate your library in a object. I am using it with my Processing project called Freeliner, its a slightly complicated but feature full projection mapping software. I am using your library to create a GUI in a browser, this has many advantages! Websockets are perfect as all is needed is a browser. Perhaps I make a pull request when I have time and would include a JS example :)
https://github.com/maxdee/alc_freeliner/tree/devel
This is where I implemented your library.
https://github.com/maxdee/alc_freeliner/blob/devel/freeliner_sketch/Communicator.pde
And here is some videos of what freeliner can do!
https://vine.co/tags/alcfreeliner

**Comment by 7thCrook** [comment]
Good morning!
    I'm using your code on a RaspBerry Pi. can you possibly post a dummies guide to your code/ sending data? maybe put a different example up that uses your code to send different data? or used in a different way? I'm just looking for some insite into sending data without getting a masters degree in networking. 
teach me...   0_0

**Comment by lassevestergaard** [comment]
Hi 7thCrook

It's great that you are using the library!

I am a little hung up these days, but will try to add some extra examples, when ever I get the time. Maybe I could help if you elaborate your issue a little.

**Comment by 7thCrook** [comment]
your very generous to think my issue is anything other than ignorance.
       i have been using processing for a while now and have a good grasp on programming as a whole "I think." however i have several projects that involve transferring data between programs on the same computer and over a network. the library you provided sounds like it will fit my needs i just am not sure how to use it correctly. i think its just my lack of knowledge on networking in general. 
 a project i would like to network is shown at the link below
https://3dprint.com/118388/3d-printed-v8-solenoid-engine/

right now id like to send several sensor feeds "streaming floats" from one program to another. i can probably figure it out if you can wise me up on how to use this library. 
i have so many projects in mind with this capability down the road, right now i just need the basics.

 server side
 ws= new WebsocketServer(this,8025,"/john"); 
what are the parameters? (this device?,PORT?,location?)

client side
wsc= new WebsocketClient(this, "ws://localhost:8025/john")
ws://localhost:8025/john"      <--- how does this work if i wanted to change it?

 .sendMessage(" data here"); 
 is this the only way to send data?
 all data has to be in string format? 
what if i wanted to send data to just one of 5 client programs? 

void webSocketEvent(String msg)
what does this do?
is it a necessity?
how do i properly use it?

**Comment by hamoid** [comment]
> I would simply like to be able to encapsulate your library in a object

This should now be possible with the latest version. It's documented in the README page.
