### ISSUE TITLE
IP address of sender?

### ISSUE THREAD

**Issue by combatistor** [alexandrainst/processing_websockets#11]
Could we get the IP address of the sender in the webSocketServerEvent() method, when we use the library as a WebSocket server?
Or have access to the list of the clients and get a notification whenever a message is received by the server.

Thank you very much, this library is a good alternative for the use of UDP communication, especially for web development.

**Comment by hamoid** [comment]
I'm looking at making some changes to the library. It's been a while, are you still interested in this?

What would be the workflow? One thing I could add is a 

    webSocketJoinEvent(String ip);
    webSocketLeaveEvent(String ip);

But I think ip is not a good option, as you could open several clients from the same ip address. Better might be to generate a unique random session ID, and transmit that instead. Then you could send messages to that specific ID. I think that's what I did with socket.io... What do you think?

**Comment by combatistor** [comment]
Hi, thank you for your reply.
getting the IP might be good to identify which device is sending what, but having a session ID is also nice. 
What about combining both?

**Comment by hamoid** [comment]
Good idea, I'll send two arguments: UID and IP. I have it working, but somehow the disconnect method doesn't get called. I'll try figure out why. I also implemented sending messages to a specific UID. More soon.

**Comment by combatistor** [comment]
Thank you so much!
I'm looking forward to trying the new version

**Comment by hamoid** [comment]
:) For now you could install it manually from
https://github.com/hamoid/processing_websockets/
Note the updated readme.

**Comment by hamoid** [comment]
One thing that could be improved though is that the UID changes when the user reconnects. I haven't studied how other libraries maintain a UID even after disconnection and reconnection. Maybe Jetty does that internally, but I didn't figure it out. I only generate a UID upon connection. This UID can be used to target a specific user.
Another useful method maybe to add is a sendToOthers(), to send a message to everyone except oneself.

**Comment by hamoid** [comment]
I see that to allow users to reconnect I should not delete them immediately upon disconnection (but only after some time), and set a cookie in their connection with the UID. Then when the user reconnects, check if the UID is found so I don't need to generate a new one.

Here's how to set cookies: https://www.eclipse.org/jetty/documentation/9.4.x/http-client-cookie.html

Or maybe there's some built in session management... will check.
