### ISSUE TITLE
jetty.log error

### ISSUE THREAD

**Issue by cjm771** [alexandrainst/processing_websockets#12]
Hi I am having trouble running this code in processing 3. I currently get:

```
[Animation Thread] INFO org.eclipse.jetty.util.log - Logging initialized @7238ms
```

Any idea on how to resolve? Thanks!

**Comment by maxdee** [comment]
I dont know if this is the right place for support, but in any case you should probably provide more details...

**Comment by Quillbert** [comment]
I don't think that's an error.

**Comment by hamoid** [comment]
It's not an error, only verbose starting of the library. It prints 5 INFO messages with red color, which looks like a typical error in the Processing IDE.

**Comment by hamoid** [comment]
I found out how to disable it:

```
		System.setProperty("org.eclipse.jetty.util.log.class",
				"org.eclipse.jetty.util.log.StdErrLog");
		System.setProperty("org.eclipse.jetty.LEVEL", "OFF");

		Server server = new Server(port);
```

I'll send a pull request.

**Comment by hamoid** [comment]
Even that doesn't seem like enough. This first answer is the only that makes it quiet:

https://stackoverflow.com/questions/2120370/jetty-how-to-disable-logging#19059551
