### ISSUE TITLE
Add event listeners for the client like onOpen and onClose

### ISSUE THREAD

**Issue by ghost** [alexandrainst/processing_websockets#14]
Please add the functions **onConnect** and **onClose** just like the webSocketEvent function to processing to make it easier to launch code when these two events occur.

**Comment by hamoid** [comment]
Hi @lycahusky, in the most recent version you should be able to use these:

```
public void webSocketConnectEvent(String uid, String ip) {
  println("Someone connected", uid, ip);
}
  
public void webSocketDisconnectEvent(String uid, String ip) {
  println("Someone disconnected", uid, ip);
}
```
